# Generated by Django 3.0.2 on 2020-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remodel', '0002_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high',
            name='sup',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vhigh',
            name='sup',
            field=models.FloatField(),
        ),
    ]
