# Generated by Django 3.0.2 on 2020-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remodel', '0004_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
