# Generated by Django 3.0.2 on 2020-05-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remodel', '0005_auto_20200502_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='high',
            old_name='id',
            new_name='ids',
        ),
    ]
