# Generated by Django 3.0.2 on 2020-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remodel', '0006_auto_20200502_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('products', models.CharField(max_length=1000)),
                ('sup', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
            ],
        ),
    ]
